### PR TITLE
chore(Dockerfile): update Grafana to 4.0.2

### PR DESCRIPTION
**Pull request by wuvs**
new core feature was added for alerts

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Comment by rimusz** [comment]
@jchauncey will grafana v4 work?
if it does, I'm happy to provide persistent storage support for influxdb/grafana charts, as we are looking to use grafana v4 too and use it's alerting.

**Comment by bacongobbler** [comment]
From their [blog post](http://grafana.org/blog/2016/12/12/grafana-4.0-stable-release/):

> # Upgrade & Breaking changes

> There are no breaking changes. Old dashboards and features should work the same. Grafana-server will automatically upgrade it’s db schema on restart. It’s advisable to do a backup of Grafana’s database before updating.

> If your are using plugins make sure to update your plugins as some might not work perfectly v4.

> You can update plugins using grafana-cli

>     grafana-cli plugins update-all

As far as I can tell we only add plugins to telegraf so no other action is necessary, though it would be good to get @jchauncey's eyes on this one when he's awake.

**Comment by bacongobbler** [comment]
If you wouldn't mind amending your commit such that it follows the [commit style guide](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#commit-style), that would be awesome! That way it'll get picked up by `deisrel` when we generate the release changelog. Thanks!

**Comment by jchauncey** [comment]
Yeah going to 4.x shouldnt be an issue as long as they didnt change the json format for dashboards (which i doubt).

**Review by jchauncey — APPROVED** [review]
I think going to 4.x is a smart move. We should just make sure the dashboards all load correctly.

**Comment by mboersma** [comment]
>  as long as they didnt change the json format for dashboards

This is why we test. :-) I'll give this a go manually.

**Comment by mboersma** [comment]
A quick smoke test doesn't show any Grafana errors, and things look the same as they did with the previous release. But since we don't have good automated coverage for monitoring changes, we should do more extensive testing to ensure there isn't a subtle issue here before merging it. We've been bitten before.

@wuvs thanks for doing this! Could you `git commit --amend` the message to something like:
```
chore(Dockerfile): update Grafana to 4.0.2
```

**Comment by vdice** [comment]
All dashboards look just fine when I deploy this change into a local cluster.

**Pull request merged**
