### PR TITLE
fix kube-create-all

### PR DESCRIPTION
**Pull request by lanej**

### CODE REVIEW

**Comment by iancoffey** [comment]
The .tmp part is intentional, this is how the dev image uri gets into the manifest for kubectl to install on your dev cluster. That part was shamelessly stolen from the [workflows Makefile](https://github.com/deis/workflow/blob/master/Makefile#L44-L46). So if we remove this, building and standing up on dev clusters would break -  maybe we can add a task for creating with the real manifests for non-vagrant use.

**Comment by lanej** [comment]
so we probably need to the `update-manifests` task as well

**Comment by lanej** [comment]
https://github.com/deis/workflow/blob/master/Makefile#L44

**Comment by iancoffey** [comment]
Yeah that part is there, also shameless cribbed. https://github.com/deis/monitor/blob/master/Makefile#L57-L61.

This workflow should work as-is to get the services up, but really only for local dev at this point.

**Comment by iancoffey** [comment]
@lanej Is this good to go?

**Pull request merged**
