### PR TITLE
chore(Dockerfile): update Influxdb to 1.1.1

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by sstarcher** [comment]
LGTM

**Comment by bacongobbler** [comment]
From the [1.1.0 release notes](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md):

> ## Configuration Changes
> The following configuration changes may need to changed before upgrading to 1.1.0 from prior versions.
> ### `[admin]` Section
> `enabled` now default to false. If you are currently using the admin interaface, you will need to change this value to true to re-enable it. The admin interface is currently deprecated and will be removed in a subsequent release.
> ### `[data]` Section
> - `cache-max-memory-size` has been increased to from 524288000 to 1048576000. This setting is the maximum amount of RAM, in bytes, a shard cache can use before it rejects writes with an error. Setting this value to 0 disables the limit.
> - `cache-snapshot-write-cold-duration` has been decreased from 1h to 10m. This setting determines how long values will stay in the shard cache while the shard is cold for writes.
> - `compact-full-write-cold-duration` has been decreased from 24h to 4h. The shorter duration allows cold shards to be compacted to an optimal state more quickly.

Can you please change the `[admin]` section such that it is disabled by default, and update the fields in the `[data]` section here: https://github.com/deis/monitor/blob/master/influxdb/rootfs/home/influxdb/config.toml.tpl

**Comment by bacongobbler** [comment]
ping

**Comment by rimusz** [comment]
so how missed your comment, will do that tomorrow

**Comment by rimusz** [comment]
no idea whats wrong with github today, cannot see my latest changes v1.1.1, going to open another PR and close this one

**Comment by rimusz** [comment]
closing in favour of #174

**Pull request closed without merging**
