### PR TITLE
chore(Dockerfile): update Grafana to 4.3.2

### PR DESCRIPTION
**Pull request by avi-jain**

### CODE REVIEW

**Comment by deis-admin** [comment]
Thanks for the contribution! Please ensure your commits follow our [style guide](http://docs.deis.io/en/latest/contributing/standards/#commit-style-guide). This code will be tested once a Deis maintainer reviews it.

**Review by jchauncey — APPROVED** [review]

**Comment by jchauncey** [comment]
cc @mboersma @vdice

**Review by jchauncey — APPROVED** [review]

**Comment by avi-jain** [comment]
I noticed this along with the older influx version being used. v1.2 brings in subqueries. Would you like me to send a PR for the same or update that?

**Comment by jchauncey** [comment]
You could just update this PR with that change too if you want.

**Comment by vdice** [comment]
Jenkins, OK to test

**Comment by vdice** [comment]
@avi-jain Thanks for the PR!  LGTM, just going to kick off CI to make sure it's happy.  I'll assume a follow-up PR for bumping influxdb will be separate...

**Pull request merged**
