### PR TITLE
chore(grafana): Add improved kubernetes health dashboard

### PR DESCRIPTION
**Pull request by jchauncey**
Test Steps:
- clone pr 
- `cd grafana && make build push upgrade`
- go to `grafana.domain.com` login using `admin/admin`
- make sure there is a kubernetes health dashboard

### CODE REVIEW

**Comment by vdice** [comment]
@jchauncey currently the `Kubernetes Health` dashboard starts from 'Last 6 hours', yet the rest of the dashboards are 'Last 5 minutes' -- should we do the same here?

**Comment by jchauncey** [comment]
Yeah I'll submit a diff pr for that

**Comment by mboersma** [comment]
> the rest of the dashboards are 'Last 5 minutes' 

Could this PR be updated to include that? Or at least create an issue to track that we want to sync that up soon?

Otherwise LGTM.

**Comment by jchauncey** [comment]
@mboersma updated pr

**Comment by mboersma** [comment]
Tested on top of Workflow v2.8.0. All dashboards appear to be working and have the same "last 3 hours" time scale.

**Pull request merged**
